version: '{build}'
image: Visual Studio 2015

install:
  - set QTDIR=C:\Qt\5.9.2\mingw53_32
  - set BOOST_PATH=C:\Libraries\boost_1_63_0
  - set PATH_ORIG=%PATH%
  - set PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin
build_script:
  - set WORKPATH=%cd%
  - echo *** boost ***
  - cd %BOOST_PATH%
  - cd tools\build
  - .\bootstrap.bat gcc
  - .\b2.exe install toolset=gcc --prefix=%BOOST_PATH%\b2_mingw
  - cd ..
  - cd ..
  - set PATH=%PATH%;%BOOST_PATH%\b2_mingw\bin
  - b2 toolset=gcc --build-type=complete link=static threading=multi variant=release --layout=tagged stage --with-system --with-filesystem --with-program_options --with-thread --with-chrono
  - ls stage\lib
  - cd %WORKPATH%
  - md boost_1_63_win
  - cd boost_1_63_win
  - copy %BOOST_PATH%\stage\lib\*.a .
  - dir
  - cd ..
  - set PATH=%PATH_ORIG%
  - 7z a boost_1_63_win.zip boost_1_63_win
  - echo *** miniupnpc ***
  - curl -fsSL -o miniupnpc-2.0.tar.gz http://miniupnp.free.fr/files/download.php?file=miniupnpc-2.0.tar.gz
  - 7z x miniupnpc-2.0.tar.gz -so | 7z x -si -ttar > nul
  - move miniupnpc-2.0 miniupnpc
  - cd miniupnpc
  - set PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin
  - perl -i -pe 's/CC \?= gcc/CC = gcc/m' Makefile.mingw
  - copy C:\MinGW\msys\1.0\bin\echo.exe upx.exe
  - mingw32make.bat
  - cd ..
  - mv miniupnpc miniupnpc_win
  - set PATH=%PATH_ORIG%
  - 7z a miniupnpc_win.zip miniupnpc_win
  - curl -fsSL -o openssl-1.0.2n.tar.gz https://www.openssl.org/source/openssl-1.0.2n.tar.gz
  - 7z x openssl-1.0.2n.tar.gz -so | 7z x -si -ttar > nul
  - move openssl-1.0.2n openssl
  - cd openssl
  - set PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin
  - sh ./config
  - make
  - cd ..
  - mv openssl openssl_win
  - set PATH=%PATH_ORIG%
  - 7z a openssl_win.zip openssl_win

artifacts:
  - path: boost_1_63_win.zip
    name: boost_1_63_win.zip

  - path: miniupnpc_win.zip
    name: miniupnpc_win.zip
