version: '{build}'
image: Visual Studio 2015

install:
  - set QTDIR=C:\Qt\5.9.2\mingw53_32
  - set BOOST_PATH=C:\Libraries\boost_1_63_0
  - set PATH_ORIG=%PATH%
  - set PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin
  - mingw-get install msys-patch
build_script:
  - set WORKPATH=%cd%
  - echo *** qt ***
  - set PATH=%PATH_ORIG%
  - curl -fsSL -o i686-5.3.0-release-posix-dwarf-rt_v4-rev0.7z https://github.com/yshurik/wbb-prebuilt-libs/releases/download/base1/i686-5.3.0-release-posix-dwarf-rt_v4-rev0.7z
  - 7z x -y i686-5.3.0-release-posix-dwarf-rt_v4-rev0.7z > nul
  - ls
  - curl -fsSL -o qt-everywhere-src-5.10.0.zip https://github.com/yshurik/wbb-prebuilt-libs/releases/download/base1/qt-everywhere-src-5.10.0.zip
  - 7z x -y qt-everywhere-src-5.10.0.zip > nul
  - set PATH=%cd%\MinGW32\bin;C:\MinGW\msys\1.0\bin;C:\Python27
  - cd qt-everywhere-src-5.10.0
  - sh ./configure -platform win32-g++ -prefix %WORKPATH%\static-qt -opensource -confirm-license -release -static -no-opengl -nomake examples -nomake tests -nomake tools -no-angle -make libs -qt-zlib -qt-pcre -qt-libpng -qt-libjpeg -qt-freetype -no-dbus -skip qtconnectivity -skip qt3d -skip qtactiveqt -skip qtcharts -skip qtdatavis3d -skip  qtdeclarative -skip qtlocation -skip qtmultimedia -skip qtpurchasing -skip qtquickcontrols -skip qtquickcontrols2 -skip qtscript -skip qtsvg -skip qtwebengine -skip qtwebchannel -skip qtwebview -skip qtxmlpatterns
  - make -j2
  - cd ..
  - fail
  - echo *** boost ***
  - cd %BOOST_PATH%
  - cd tools\build
  - .\bootstrap.bat gcc
  - .\b2.exe install toolset=gcc --prefix=%BOOST_PATH%\b2_mingw
  - cd ..
  - cd ..
  - set PATH=%PATH%;%BOOST_PATH%\b2_mingw\bin
  - b2 toolset=gcc --build-type=complete link=static threading=multi variant=release --layout=tagged stage --with-system --with-filesystem --with-program_options --with-thread --with-chrono
  - ls stage\lib
  - cd %WORKPATH%
  - md static_boost_1_63_win
  - cd static_boost_1_63_win
  - copy %BOOST_PATH%\stage\lib\*.a .
  - dir
  - cd ..
  - set PATH=%PATH_ORIG%
  - 7z a static_boost_1_63_win.zip static_boost_1_63_win
  - echo *** miniupnpc ***
  - curl -fsSL -o miniupnpc-2.0.tar.gz http://miniupnp.free.fr/files/download.php?file=miniupnpc-2.0.tar.gz
  - 7z x miniupnpc-2.0.tar.gz -so | 7z x -si -ttar > nul
  - move miniupnpc-2.0 miniupnpc
  - cd miniupnpc
  - set PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin
  - perl -i -pe 's/CC \?= gcc/CC = gcc/m' Makefile.mingw
  - copy C:\MinGW\msys\1.0\bin\echo.exe upx.exe
  - mingw32make.bat
  - cd ..
  - mv miniupnpc static_miniupnpc_win
  - set PATH=%PATH_ORIG%
  - 7z a static_miniupnpc_win.zip static_miniupnpc_win
  - echo *** openssl ***
  - curl -fsSL -o openssl-1.0.2n.tar.gz https://www.openssl.org/source/openssl-1.0.2n.tar.gz
  - 7z x openssl-1.0.2n.tar.gz -so | 7z x -si -ttar > nul
  - move openssl-1.0.2n openssl
  - cd openssl
  - set PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin
  - sh ./config
  - make
  - cd ..
  - md static_openssl_win
  - cp -r openssl/include static_openssl_win/
  - cp openssl/lib* static_openssl_win/
  - set PATH=%PATH_ORIG%
  - 7z a static_openssl_win.zip static_openssl_win
  - echo *** db-4.8 ***
  - curl -fsSL -o db-4.8.30.NC.tar.gz http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz
  - tar -zxf db-4.8.30.NC.tar.gz
  - mv db-4.8.30.NC db
  - cd db
  - cd build_unix
  - set PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin
  - sh ../dist/configure --enable-mingw --enable-cxx
  - perl -i -pe 's/REP_OBJS\) \$\(REPMGR_OBJS\) /REP_OBJS) repmgr_stub.lo /m' Makefile
  - perl -i -pe 's/define socklen_t int/define socklen_t_xx int/m' db_config.h
  - perl -i -pe 's/define HAVE_REPLICATION_THREADS 1/define HAVE_REPLICATION_THREADS_XX 1/m' db_config.h
  - cd ..
  - patch -p1 < ../patches/db-4.8.30-fix-for-mingw.patch
  - cd build_unix
  - make
  - cd ..
  - cd ..
  - md static_db_4_8_win
  - md static_db_4_8_win\include
  - cp db/build_unix/*.h static_db_4_8_win/include/
  - cp db/build_unix/lib*a static_db_4_8_win/
  - set PATH=%PATH_ORIG%
  - 7z a static_db_4_8_win.zip static_db_4_8_win

artifacts:
  - path: static_boost_1_63_win.zip
    name: static_boost_1_63_win.zip

  - path: static_miniupnpc_win.zip
    name: static_miniupnpc_win.zip

  - path: static_openssl_win.zip
    name: static_openssl_win.zip

  - path: static_db_4_8_win.zip
    name: static_db_4_8_win.zip
